name: Release
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - run: |
          echo "---\n:rubygems_api_key: $RUBYGEMS_API_KEY\n" > ~/.gem/credentials
      - run: bundle exec rake build
      - run: gem push pkg/percy-selenium-*
        env:
          RUBY_GEM_API_TOKEN: ${{ secrets.RUBYGEMS_API_KEY }}
